[tool.poetry]
name = "titanic_ml"
description = "titanic_ml example package"
version = "0.1.0"
dependencies = [
    "pyspark[ml]",
    "sklearn"
]

[tool.black]
line-length = 88
target_version = ['py36']
include = '\.pyi?$'
