name: Main workflow
on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  run:
    name: Run
    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: npm

    - name: npm ci
      run: npm ci

    - uses: actions/checkout@v3
    - name: Install poetry
      run: pipx install poetry==1.1.15
      
    - uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'poetry'
    - run: poetry install

